import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Sidebar } from '../components/Sidebar'

export default function Blog() {
  return (
    <div className={styles.container}>
      <Sidebar />
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog
        </h1>
      </main>
    </div>
  )
}