name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            cache/Cypress
          key: ${{ runner.os }}-build-${{ github.sha }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}-npm-
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12'
      - name: Install dependencies
        run: npm install

  e2e-local:
    runs-on: ubuntu-latest
    needs: prepare-dependencies
    strategy:
      matrix:
        container:
          - cypress/base:20.12.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            cache/Cypress
          key: ${{ runner.os }}-build-${{ github.sha }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}-npm-
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12'
      - name: Install Cypress binary
        run: npx cypress install
      - name: Set timezone
        run: sudo timedatectl set-timezone Asia/Taipei
      - name: Install dependencies
        run: npm install
      - name: Start application
        run: npm start &
      - name: Wait for application to be ready
        run: npx wait-on 'http-get://localhost:4321'
      - name: Run Cypress tests
        run: npx cypress run

  build_and_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: e2e-local
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}-npm-
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12'
      - name: Install dependencies
        run: npm install
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Build project
        run: npm run build
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --prod --dir=dist --site=${{ secrets.NETLIFY_SITE_ID }}
